### PR TITLE
Fix to make `create_limit_order` work

### PR DESCRIPTION
**Pull request by avaucher**
This is the minimal changes I found to solve #47.

Feel free to refactor / update as you wish.

### CODE REVIEW

**Comment by avaucher** [comment]
I updated it again, `get_accounts` works for me now.

**Comment by avaucher** [comment]
I am not sure anymore whether setting the header values was mandatory, but I think that it didn't work without it.

Modifying the post body was mandatory as well: without it, a 401 error for a signature error was raised. My guess is that the JSON body must be 100% the same as was used for generating the signature (i.e., no spaces in the JSON string).

**Comment by sammchardy** [comment]
Makes sense. I'll give it a test shortly. Feel free to add me on Telegram too @sammchardy there.

**Comment by sammchardy** [comment]
Thanks @avaucher will close this as have rolled into v2.1.0 thanks for you testing!

**Comment by avaucher** [comment]
works for me, thanks!

**Pull request closed without merging**
